# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plur < Formula
  desc "Fast parallel test runner for Ruby/RSpec"
  homepage "https://github.com/rsanheim/plur"
  version "0.46.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rsanheim/plur/releases/download/v0.46.0/plur_0.46.0_darwin_arm64.tar.gz"
      sha256 "9f9086158ece25c6d971c5019bf75beff53f3bb3af2319b774b5276d4f082649"

      define_method(:install) do
        bin.install "plur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsanheim/plur/releases/download/v0.46.0/plur_0.46.0_linux_amd64.tar.gz"
      sha256 "342ec93e83d8585b890a4da484d48cee885ecbcebb590c71e943d545fab2126c"
      define_method(:install) do
        bin.install "plur"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsanheim/plur/releases/download/v0.46.0/plur_0.46.0_linux_arm64.tar.gz"
      sha256 "fe2574cada727dc12950bf4f2b463488c61bacbd44b57ea9414b69cb8a6c66f2"
      define_method(:install) do
        bin.install "plur"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/plur --version")
  end
end
