# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plur < Formula
  desc "Fast parallel test runner for Ruby/RSpec"
  homepage "https://github.com/rsanheim/plur"
  version "0.46.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rsanheim/plur/releases/download/v0.46.1/plur_0.46.1_darwin_arm64.tar.gz"
      sha256 "d738b4e0da8a8093410597f491bd55593a961a5ad19aacd635bfe7f4a9be87df"

      define_method(:install) do
        bin.install "plur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsanheim/plur/releases/download/v0.46.1/plur_0.46.1_linux_amd64.tar.gz"
      sha256 "1c6c03aacf9a7a87a4f22abe906e01557237dbd63d81d0926808db674237834a"
      define_method(:install) do
        bin.install "plur"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsanheim/plur/releases/download/v0.46.1/plur_0.46.1_linux_arm64.tar.gz"
      sha256 "517810ff9dca9f07cb2e32cdad226f31770c9fada03efdad64a0f270d99f8a86"
      define_method(:install) do
        bin.install "plur"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/plur --version")
  end
end
