# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plur < Formula
  desc "Fast parallel test runner for Ruby/RSpec"
  homepage "https://github.com/rsanheim/plur"
  version "0.51.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rsanheim/plur/releases/download/v0.51.0/plur_0.51.0_darwin_arm64.tar.gz"
      sha256 "80958f179f9eef2ab238774bfc9811f1bd4ffe015d0f7e6d438d0d507a09d874"

      define_method(:install) do
        bin.install "plur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsanheim/plur/releases/download/v0.51.0/plur_0.51.0_linux_amd64.tar.gz"
      sha256 "4488bd9fe32673f923d202d905e885a6549fb2e151eccdd1c295ca2ea2e93952"
      define_method(:install) do
        bin.install "plur"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsanheim/plur/releases/download/v0.51.0/plur_0.51.0_linux_arm64.tar.gz"
      sha256 "b8f3d3f2f6906c7a41f66731b128c5a35ecd52e45214c7397b2c0fa131fe0940"
      define_method(:install) do
        bin.install "plur"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/plur --version")
  end
end
