name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Run brew audit
        run: |
          brew audit --strict rsanheim/tap/git-all
          brew audit --strict rsanheim/tap/plur

      - name: Run brew style
        run: |
          brew style rsanheim/tap/git-all
          brew style rsanheim/tap/plur

      - name: Run brew readall
        run: brew readall --os=all --arch=all rsanheim/tap

      - name: Run brew install/test
        run: |
          brew install rsanheim/tap/git-all
          brew test rsanheim/tap/git-all
